# Generated by Django 3.2.9 on 2022-01-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndexHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('subject', models.TextField(max_length=100)),
                ('body', models.TextField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
