# Generated by Django 3.2.9 on 2021-12-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndexHome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribe_newsletter',
        ),
    ]
