# Generated by Django 3.2.5 on 2021-08-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndexHome', '0002_auto_20210727_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribe_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Code',
        ),
    ]
