# Generated by Django 3.2.9 on 2021-11-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndexHome', '0003_auto_20210831_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fail_otp_request',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.TextField(default='xxxxxx'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resend_otp_request',
            field=models.SmallIntegerField(default=0),
        ),
    ]
