# Generated by Django 3.2.9 on 2021-11-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndexHome', '0004_auto_20211114_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.TextField(default='xxxxxx', max_length=100),
        ),
    ]
