# Generated by Django 3.2.9 on 2021-11-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndexHome', '0005_auto_20211114_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key',
            field=models.BinaryField(),
        ),
    ]
