# Generated by Django 3.2.9 on 2021-11-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndexHome', '0007_auto_20211114_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key',
            field=models.BinaryField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.TextField(default=None, max_length=6),
        ),
    ]
