# Generated by Django 3.2.9 on 2021-11-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndexHome', '0008_auto_20211116_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key',
            field=models.TextField(default='empty', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.TextField(default='xxxxxx', max_length=6),
        ),
    ]
