# Generated by Django 3.2.9 on 2021-11-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndexHome', '0009_auto_20211116_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fail_attepmt',
            field=models.SmallIntegerField(default=0),
        ),
    ]
