# Generated by Django 3.2.9 on 2022-01-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default='', max_length=200)),
                ('github_username', models.TextField(default='', max_length=40)),
            ],
        ),
    ]
