# Generated by Django 3.2.9 on 2021-12-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_profile_register_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_register',
            name='username',
        ),
        migrations.AddField(
            model_name='profile_register',
            name='github_username',
            field=models.TextField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile_register',
            name='user',
            field=models.TextField(max_length=200),
        ),
    ]
