# Generated by Django 3.2.5 on 2021-07-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_snipet',
            field=models.CharField(default='bolgsnippet', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='entry_img',
            field=models.CharField(default='img field', max_length=500),
        ),
    ]
