# Generated by Django 3.2.5 on 2021-07-20 03:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210720_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_snipet',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='entry_img',
            field=models.CharField(max_length=500),
        ),
    ]
