# Generated by Django 3.2.5 on 2021-07-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210720_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='entry_img',
            field=models.URLField(max_length=500),
        ),
    ]
