# Generated by Django 3.2.5 on 2021-07-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_entry_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_conculsion',
            field=models.CharField(default='No Author Review', max_length=300),
        ),
    ]
