# Generated by Django 3.2.5 on 2021-07-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_author_conculsion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readtime_min',
            field=models.IntegerField(default=0),
        ),
    ]
