# Generated by Django 3.2.5 on 2021-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210727_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editor_choice',
            field=models.BooleanField(default=False),
        ),
    ]
