# Generated by Django 3.2.5 on 2021-08-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
