# Generated by Django 3.2.5 on 2021-08-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_likes_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
