# Generated by Django 3.2.9 on 2021-11-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='post',
            name='skills',
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_snipet',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
