errors_mssg = [
    # 1  ("Unauthorized access","back to home"),
    # 2  ("bypass blocked",""),
    # 3  ("Account already linked with this email",""),
    # 4  ("Oops! somethings went wrong ,contact support",""),
    # 5  ("Logout Successfully!!",""),
    # 6  ("First verify your account to request forgot-password",""),
    # 7  ("No account linked with this email",""),
    # 8  ("forgot-password request failed",""),
    # 9  ("Unauthorized request",""),
    # 10 ("Password changed successfully",""),
    # 11 ("Notify register successfully",""),
    # 12 ("Notify request Failed!!",""),
    # 13 ("Newsletter subscribed!!",""),
    # 15 ("Account not verified",""),
    # 16 ("incorrect email or password",""),
    # 17 ("Max OTP requested. Verification failed",""),
    # 18 ("Verification failed user not verified Contact Support!",""),
    # 19 ("incorrect verification code","")
]